# Generated by Django 6.0.5 on 2026-05-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('doc_type', models.CharField(choices=[('INV', 'Счет-фактура'), ('CTR', 'Договор'), ('AGR', 'Соглашение')], max_length=3, verbose_name='Тип документа')),
                ('description', models.TextField(blank=True, max_length=5096, null=True, verbose_name='Описание')),
                ('version', models.IntegerField(default=1, verbose_name='Версия')),
                ('link_file', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Ссылка на документ')),
                ('datetime_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('datetime_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'db_table': 'document',
            },
        ),
    ]
